# Linear Regression From Scratch

## importing the libraries

In [15]:
import pandas as pd
import numpy as np

In [16]:
file1 = pd.read_csv('https://raw.githubusercontent.com/AshishJangra27/Machine-Learning-with-Python-GFG/main/Linear%20Regression/data_for_lr.csv')

In [17]:
file1.head()

x          y
0  24.0  21.549452
1  50.0  47.464463
2  15.0  17.218656
3  38.0  36.586398
4  87.0  87.288984

In [18]:
file1.tail()

x          y
695  58.0  58.595006
696  93.0  94.625094
697  82.0  88.603770
698  66.0  63.648685
699  97.0  94.975266

In [19]:
file1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   x       700 non-null    float64
 1   y       699 non-null    float64
dtypes: float64(2)
memory usage: 11.1 KB


In [20]:
file1.describe()

x           y
count   700.000000  699.000000
mean     54.985939   49.939869
std     134.681703   29.109217
min       0.000000   -3.839981
25%      25.000000   24.929968
50%      49.000000   48.973020
75%      75.000000   74.929911
max    3530.157369  108.871618

In [21]:
file1.dropna(inplace=True)

In [22]:
file1.shape

(699, 2)

## Training input and output.

In [23]:
training_input = file1.iloc[:501, :-1].values

In [24]:
training_input

array([[ 24.],
       [ 50.],
       [ 15.],
       [ 38.],
       [ 87.],
       [ 36.],
       [ 12.],
       [ 81.],
       [ 25.],
       [  5.],
       [ 16.],
       [ 16.],
       [ 24.],
       [ 39.],
       [ 54.],
       [ 60.],
       [ 26.],
       [ 73.],
       [ 29.],
       [ 31.],
       [ 68.],
       [ 87.],
       [ 58.],
       [ 54.],
       [ 84.],
       [ 58.],
       [ 49.],
       [ 20.],
       [ 90.],
       [ 48.],
       [  4.],
       [ 25.],
       [ 42.],
       [  0.],
       [ 60.],
       [ 93.],
       [ 39.],
       [  7.],
       [ 21.],
       [ 68.],
       [ 84.],
       [  0.],
       [ 58.],
       [ 19.],
       [ 36.],
       [ 19.],
       [ 59.],
       [ 51.],
       [ 19.],
       [ 33.],
       [ 85.],
       [ 44.],
       [  5.],
       [ 59.],
       [ 14.],
       [  9.],
       [ 75.],
       [ 69.],
       [ 10.],
       [ 17.],
       [ 58.],
       [ 74.],
       [ 21.],
       [ 51.],
       [ 19.],
       [ 50.],
       [ 2

In [25]:
training_output = file1.loc[:501, "y":].values

In [26]:
training_output

array([[ 21.54945196],
       [ 47.46446305],
       [ 17.21865634],
       [ 36.58639803],
       [ 87.28898389],
       [ 32.46387493],
       [ 10.78089683],
       [ 80.7633986 ],
       [ 24.61215147],
       [  6.96331907],
       [ 11.23757338],
       [ 13.53290206],
       [ 24.60323899],
       [ 39.40049976],
       [ 48.43753838],
       [ 61.69900319],
       [ 26.92832418],
       [ 70.4052055 ],
       [ 29.34092408],
       [ 25.30895192],
       [ 69.02934339],
       [ 84.99484703],
       [ 57.04310305],
       [ 50.5921991 ],
       [ 83.02772202],
       [ 57.05752706],
       [ 47.95883341],
       [ 24.34226432],
       [ 94.68488281],
       [ 48.03970696],
       [  7.08132338],
       [ 21.99239907],
       [ 42.33151664],
       [  0.32908944],
       [ 61.92303698],
       [ 91.17716423],
       [ 39.45358014],
       [  5.99606961],
       [ 22.59015942],
       [ 61.18044414],
       [ 85.02778957],
       [ -1.28631089],
       [ 61.94273962],
       [ 21

In [27]:
testing_input = file1.iloc[501:, :-1].values

In [28]:
testing_input

array([[ 61.],
       [ 47.],
       [ 98.],
       [ 30.],
       [ 63.],
       [  0.],
       [100.],
       [ 18.],
       [ 30.],
       [ 98.],
       [ 16.],
       [ 22.],
       [ 55.],
       [ 43.],
       [ 75.],
       [ 91.],
       [ 46.],
       [ 85.],
       [ 55.],
       [ 36.],
       [ 49.],
       [ 94.],
       [ 43.],
       [ 22.],
       [ 37.],
       [ 24.],
       [ 95.],
       [ 61.],
       [ 75.],
       [ 68.],
       [ 58.],
       [  5.],
       [ 53.],
       [ 80.],
       [ 83.],
       [ 25.],
       [ 34.],
       [ 26.],
       [ 90.],
       [ 60.],
       [ 49.],
       [ 19.],
       [ 92.],
       [ 29.],
       [  8.],
       [ 57.],
       [ 29.],
       [ 19.],
       [ 81.],
       [ 50.],
       [ 15.],
       [ 70.],
       [ 39.],
       [ 43.],
       [ 21.],
       [ 98.],
       [ 86.],
       [ 16.],
       [ 25.],
       [ 31.],
       [ 93.],
       [ 67.],
       [ 49.],
       [ 25.],
       [ 88.],
       [ 54.],
       [ 2

In [29]:
testing_output = file1.iloc[501:, -1:].values

In [30]:
testing_output

array([[ 61.01858089],
       [ 53.60562216],
       [ 94.47728801],
       [ 27.9645947 ],
       [ 62.55662585],
       [  1.40625441],
       [101.7003412 ],
       [ 13.84973988],
       [ 28.99769315],
       [ 99.04315693],
       [ 15.56135514],
       [ 24.63528393],
       [ 53.98393374],
       [ 42.91449728],
       [ 74.29662112],
       [ 91.17012883],
       [ 49.42440876],
       [ 82.47683519],
       [ 56.15303953],
       [ 37.17063131],
       [ 46.36928662],
       [ 97.02383456],
       [ 40.83182104],
       [ 24.08498313],
       [ 41.14386358],
       [ 21.97388066],
       [100.740897  ],
       [ 61.19971596],
       [ 74.39517002],
       [ 69.04377173],
       [ 56.68718792],
       [  5.86039171],
       [ 55.72021356],
       [ 79.22021816],
       [ 86.30177517],
       [ 25.26971886],
       [ 36.33294447],
       [ 27.65574228],
       [ 94.79690531],
       [ 58.67366671],
       [ 56.15934471],
       [ 18.40919388],
       [ 86.26936988],
       [ 26

In [31]:
def forwardPropagation(train_input, m, c):
    predictions = np.multiply(train_input , m) + c
    return predictions


def costFunction(train_output, predictions):
    cost = np.mean((train_output - predictions) ** 2) * 0.5
    return cost

In [32]:
def backwardPropagation(train_input, train_output,  predictions):
    derivatives = dict()
    
    df = predictions - train_output
    dm = np.mean(np.multiply(df, train_input))
    dc = np.mean(df)
    
    derivatives['dm'] = dm
    derivatives['dc'] = dc
    
    return derivatives

In [33]:
def updateParameters(parameters, derivatives, learning_rate):
    parameters['m'] = parameters['m'] - (learning_rate*derivatives['dm'])
    parameters['c'] = parameters['c'] - (learning_rate*derivatives['dc'])
    
    return parameters

In [34]:
def train(train_input, train_output, learning_rate, iters):
    
    parameters = dict()
    loss = []
    
    parameters['m'] = np.random.uniform(0, 1)
    parameters['c'] = np.random.uniform(0, 1)
    
    for i in range(iters):
        predictions = forwardPropagation(train_input=train_input, m = parameters['m'], c = parameters['c'])
        
        cost = costFunction(train_output=train_output, predictions=predictions)
        loss.append(cost)
        
        derivatives = backwardPropagation(train_input, train_output, predictions)
        
        parameters = updateParameters(parameters, derivatives, learning_rate)
        
        
    return parameters, loss

In [45]:
parameters, loss = train(training_input, training_output, 0.0001, 100)

In [46]:
parameters

{'m': 0.9849473907692632, 'c': 0.8245001441046717}