In [2]:
import pandas as pd
import numpy as np
import sklearn as sk

In [3]:
file1 = pd.read_csv('https://raw.githubusercontent.com/AshishJangra27/Machine-Learning-with-Python-GFG/main/Linear%20Regression/data_for_lr.csv')

In [4]:
file1.dropna(inplace = True)

In [5]:
file1

x          y
0    24.0  21.549452
1    50.0  47.464463
2    15.0  17.218656
3    38.0  36.586398
4    87.0  87.288984
..    ...        ...
695  58.0  58.595006
696  93.0  94.625094
697  82.0  88.603770
698  66.0  63.648685
699  97.0  94.975266

[699 rows x 2 columns]

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(file1.iloc[:,:-1].values, file1.iloc[:,1:].values, test_size=0.3)

In [8]:
lr_model = LinearRegression()

In [9]:
lr_model.fit(X_train, y_train)

LinearRegression()

In [10]:
lr_model.coef_

array([[0.99921504]])

In [11]:
lr_model.intercept_

array([0.05713953])

In [12]:
X_train

array([[ 99.],
       [ 54.],
       [ 77.],
       [ 46.],
       [ 65.],
       [ 28.],
       [ 61.],
       [100.],
       [ 35.],
       [ 51.],
       [ 46.],
       [ 81.],
       [  8.],
       [ 94.],
       [ 60.],
       [ 42.],
       [ 96.],
       [ 99.],
       [ 96.],
       [ 10.],
       [ 34.],
       [ 31.],
       [ 87.],
       [ 19.],
       [ 39.],
       [ 41.],
       [ 37.],
       [  8.],
       [ 72.],
       [ 48.],
       [ 47.],
       [ 16.],
       [ 87.],
       [ 87.],
       [ 46.],
       [ 48.],
       [ 10.],
       [ 50.],
       [ 25.],
       [ 47.],
       [ 26.],
       [ 78.],
       [ 93.],
       [ 54.],
       [ 39.],
       [ 70.],
       [ 62.],
       [ 59.],
       [ 24.],
       [  6.],
       [ 58.],
       [ 70.],
       [ 67.],
       [  0.],
       [ 89.],
       [ 13.],
       [ 16.],
       [ 51.],
       [ 81.],
       [ 65.],
       [ 71.],
       [ 16.],
       [ 65.],
       [ 56.],
       [ 26.],
       [ 79.],
       [ 5

In [13]:
lr_model.predict(X_train)

array([[9.89794287e+01],
       [5.40147518e+01],
       [7.69966977e+01],
       [4.60210315e+01],
       [6.50061172e+01],
       [2.80351607e+01],
       [6.10092571e+01],
       [9.99786437e+01],
       [3.50296660e+01],
       [5.10171067e+01],
       [4.60210315e+01],
       [8.09935579e+01],
       [8.05085987e+00],
       [9.39833535e+01],
       [6.00100420e+01],
       [4.20241713e+01],
       [9.59817835e+01],
       [9.89794287e+01],
       [9.59817835e+01],
       [1.00492900e+01],
       [3.40304510e+01],
       [3.10328058e+01],
       [8.69888482e+01],
       [1.90422253e+01],
       [3.90265262e+01],
       [4.10249562e+01],
       [3.70280961e+01],
       [8.05085987e+00],
       [7.20006225e+01],
       [4.80194615e+01],
       [4.70202465e+01],
       [1.60445802e+01],
       [8.69888482e+01],
       [8.69888482e+01],
       [4.60210315e+01],
       [4.80194615e+01],
       [1.00492900e+01],
       [5.00178916e+01],
       [2.50375156e+01],
       [4.70202465e+01],


In [14]:
predictions = lr_model.predict(X_test)
for i in range(len(X_test)):
    print(f"{X_test[i]} : {y_test[i]}, {predictions[i]}")

[70.] : [75.0284725], [70.00219245]
[24.] : [21.81267954], [24.03830053]
[90.] : [91.19109623], [89.98649329]
[73.] : [72.80457527], [72.99983758]
[39.] : [39.45358014], [39.02652616]
[21.] : [18.44679787], [21.04065541]
[95.] : [91.775467], [94.98256849]
[47.] : [44.15029394], [47.02024649]
[32.] : [28.41453196], [32.03202087]
[40.] : [39.69185252], [40.0257412]
[44.] : [44.04222058], [44.02260137]
[49.] : [52.50336074], [49.01867658]
[45.] : [43.9367213], [45.02181641]
[57.] : [56.18131518], [57.01239691]
[62.] : [66.48278755], [62.00847212]
[5.] : [7.38224417], [5.05321474]
[40.] : [43.30022747], [40.0257412]
[99.] : [99.11200375], [98.97942866]
[5.] : [6.96331907], [5.05321474]
[51.] : [55.85003198], [51.01710666]
[80.] : [77.13735466], [79.99434287]
[5.] : [1.61194747], [5.05321474]
[58.] : [55.61421297], [58.01161195]
[86.] : [86.12955884], [85.98963312]
[19.] : [20.87391785], [19.04222533]
[27.] : [25.77161074], [27.03594566]
[44.] : [41.57421008], [44.02260137]
[45.] : [46.0537

In [15]:
from sklearn.metrics import mean_squared_error


mean_squared_error(y_test, predictions)

8.088137635689097