In [ ]:
# Getting started with Numpy
# 
# numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.
# Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data.
# 
# 
# 
# If you do not have numpy installed in your system first you need to install it.
# 
# !pip install numpy
# 
# A list in Python is a linear data structure that can hold heterogeneous elements they do not require to be declared and are flexible to shrink and grow. On the other hand, an array is a data structure which can hold homogeneous elements, arrays are implemented in Python using the NumPy library. Arrays require less memory than list.
# 
# The similarity between an array and a list is that the elements of both array and a list can be identified by its index value.
# 
# 
# 
# Now let us convert a list into an array
# 
# import numpy as np
# 
# l=[2,3,4,5]
# print(l)
# print(type(l))
# print()
# arr=np.array(l)
# print(arr)
# print(type(arr))
# Output:
# 
# [2, 3, 4, 5]
# <class 'list'>
# 
# [2 3 4 5]
# <class 'numpy.ndarray'>
# So we have first printed the list and then converted the list to an array and displayed that as well
# 
# 
# 
# 
# 
# numpy.ndarray.ndim() function return the number of dimensions of an array.
# 
# Syntax : numpy.ndarray.ndim(arr)
# 
# Parameters :
# arr : [array_like] Input array. If it is not already an ndarray, a conversion is attempted.
# 
# Return : [int] Return the number of dimensions in arr.
# 
# a=np.array([1,2,3,4])
# b=np.array([[1,2,3,4],[5,6,7,8]])
# print(a.ndim)
# print(b.ndim)
# Output:
# 
# 1
# 2
# So we can the dimension of array a is 1 dimension and the array b is 2 dimention
# 
# 
# 
# 
# 
# Now we have few more functions such as np.array.shape, np.array.size and np.array.dtype
# 
# shape will basically return us the total number of rows and columns of the array in a tuple format (number of rows, number of columns)
# 
# size will tell us the total number of elements or values present in the array
# 
# dtype will tell us the data type of values which the array is containing
# 
# 
# 
# Let's see the implementation of all these
# 
# b=np.array([[1,2,3,4],[5,6,7,8]])
# print(b.shape)
# print(b.size)
# print(b.dtype)
# 
# 
# Output:
# 
# (2, 4)
# 8
# int32
# So we have 2 rows and 4 columns in the array b
# We have 8 elements present in the array
# The data type of the elements present in the array is int
# 
# 
# 
# 
# The numpy.zeros() function returns a new array of given shape and type, with zeros. Syntax:
# 
# numpy.zeros(shape, dtype = None, order = 'C')
# Parameters :
# 
# 
# 
# shape : integer or sequence of integers
# order  : C_contiguous or F_contiguous
# C-contiguous order in memory(last index varies the fastest)
# C order means that operating row-rise on the array will be slightly quicker
# FORTRAN-contiguous order in memory (first index varies the fastest).
# F order means that column-wise operations will be faster.
# dtype : [optional, float(byDeafult)] Data type of returned array.
# Returns :
# 
# ndarray of zeros having given shape, order and datatype.
# 
# # Python Program illustrating
# # numpy.zeros method
# 
# import numpy as geek
# 
# b = geek.zeros(2, dtype = int)
# print("Matrix b : \n", b)
# 
# a = geek.zeros([2, 2], dtype = int)
# print("\nMatrix a : \n", a)
# 
# c = geek.zeros([3, 3])
# print("\nMatrix c : \n", c)
# 
# 
# Output :
# 
# Matrix b :
# [0 0]
# 
# Matrix a :
# [[0 0]
#  [0 0]]
# 
# Matrix c :
# [[ 0.  0.  0.]
#  [ 0.  0.  0.]
# [ 0.  0.  0.]]
# 
# 
# 
# 
# The numpy.ones() function returns a new array of given shape and type, with ones.
# 
# 
# Syntax: numpy.ones(shape, dtype = None, order = 'C')
# Parameters :
# 
# shape : integer or sequence of integers
# order  : C_contiguous or F_contiguous
# C-contiguous order in memory(last index varies the fastest)
# C order means that operating row-rise on the array will be slightly quicker
# FORTRAN-contiguous order in memory (first index varies the fastest).
# F order means that column-wise operations will be faster.
# dtype : [optional, float(byDefault)] Data type of returned array.
# Returns :
# 
# 
# ndarray of ones having given shape, order and datatype.
# 
# 
# 
# # Python Program illustrating
# # numpy.ones method
# 
# import numpy as geek
# 
# b = geek.ones(2, dtype = int)
# print("Matrix b : \n", b)
# 
# a = geek.ones([2, 2], dtype = int)
# print("\nMatrix a : \n", a)
# 
# c = geek.ones([3, 3])
# print("\nMatrix c : \n", c)
# 
# 
# Output :
# 
# 
# Matrix b :
# [1 1]
# 
# Matrix a :
# [[1 1]
#  [1 1]]
# 
# Matrix c :
# [[ 1.  1.  1.]
#  [ 1.  1.  1.]
# [ 1.  1.  1.]]

In [2]:
import numpy as np

# Creating numpy array using a list.

lst = [1,2,3,4]

narray = np.array(lst)
print(narray)

# Type of narray

print(type(narray))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
narray2 = np.ndarray([2,4])
print(narray2)

[[4.67296746e-307 1.69121096e-306 1.86921822e-306 1.42413555e-306]
 [1.78019082e-306 1.37959740e-306 6.23057349e-307 1.42419530e-306]]


In [3]:
narray3 = np.arange(1,10,step=5)
print(narray3)

[1 6]


In [22]:
array = narray.reshape(2,2)
print(array)
print(array.ndim)
array2 = narray.reshape(4)
print(array2)
print(array2.ndim)

[[1 2]
 [3 4]]
2
[1 2 3 4]
1


In [30]:
# Shape of the array.
print(array.shape)

# Size of the array.
print(array.size)

# data type of the array.
print(array.dtype)

(2, 2)
4
int32


In [32]:
# Creating an array of zeros with given dimensions.

array3 = np.zeros([2,4])
array3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
# Creating an array of ones with given dimensions.

array4 = np.ones([3,3])
array4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
# Creating an random array.

array4 = np.random.random([3,7])
array4

array([[0.05474675, 0.25690697, 0.57682444, 0.47130136, 0.565466  ,
        0.77829046, 0.43338499],
       [0.39728643, 0.00876391, 0.18902724, 0.36718333, 0.9704806 ,
        0.56832122, 0.99342899],
       [0.60139193, 0.54324913, 0.1966487 , 0.67534928, 0.97696805,
        0.28927873, 0.15872989]])

In [65]:
rnum = np.random.randint(989,1000)
rnum

991

In [16]:
array5 = np.arange(1,100)
print(array5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [17]:
array6 = np.linspace(1,100,2)
print(array6)

[  1. 100.]


In [24]:
array7 = array6.reshape([2,1])
print(array7)

[[  1.]
 [100.]]


In [30]:
# Using a flatten function, we can convert a dim array to 1dim array.

array8 = array4.flatten()
print(array8)
print(f"Dim of the array8 : {array8.ndim}")

[0.05474675 0.25690697 0.57682444 0.47130136 0.565466   0.77829046
 0.43338499 0.39728643 0.00876391 0.18902724 0.36718333 0.9704806
 0.56832122 0.99342899 0.60139193 0.54324913 0.1966487  0.67534928
 0.97696805 0.28927873 0.15872989]
Dim of the array8 : 1


#### Arithmetic operations on array.


In [51]:
from scipy import stats as st


array9 = np.random.random([1,9])
print(f"Sum of array9 : {array9.sum()}")
print(f"Max of array9 : {array9.max()}")
print(f"Min of array9 : {array9.min()}")
print(f"Mean of array 9 : {array9.mean()}")
print(f"Median of array9 : {np.median(array9)}")
print(f"Mode of array9 : {st.mode(array9)}")

Sum of array9 : 6.716507889528301
Max of array9 : 0.9361454927974351
Min of array9 : 0.5324271945281202
Mean of array 9 : 0.7462786543920334
Median of array9 : 0.7785723463411951
Mode of array9 : ModeResult(mode=array([0.85324821, 0.6302599 , 0.62412832, 0.93614549, 0.53242719,
       0.77857235, 0.86996947, 0.93321962, 0.55853734]), count=array([1., 1., 1., 1., 1., 1., 1., 1., 1.]))


In [52]:
# Adding a number to every element of the array.

print(array9)
array9 = array9 + 1
print(array9)

[[0.85324821 0.6302599  0.62412832 0.93614549 0.53242719 0.77857235
  0.86996947 0.93321962 0.55853734]]
[[1.85324821 1.6302599  1.62412832 1.93614549 1.53242719 1.77857235
  1.86996947 1.93321962 1.55853734]]


In [53]:
# Subtraction

array9 = array9 - 2
print(array9)

[[-0.14675179 -0.3697401  -0.37587168 -0.06385451 -0.46757281 -0.22142765
  -0.13003053 -0.06678038 -0.44146266]]


In [54]:
# Multiplication

array9 = array9 * -10
print(array9)

[[1.46751793 3.69740104 3.75871679 0.63854507 4.67572805 2.21427654
  1.30030528 0.6678038  4.41462662]]


In [55]:
# Division

array9 = array9 / 10
print(array9)

[[0.14675179 0.3697401  0.37587168 0.06385451 0.46757281 0.22142765
  0.13003053 0.06678038 0.44146266]]


In [56]:
array9 %= 10
print(array9)

[[0.14675179 0.3697401  0.37587168 0.06385451 0.46757281 0.22142765
  0.13003053 0.06678038 0.44146266]]


In [59]:
# Finding the max and min in row and coloumn wise.

array10 = np.random.random([3,3])
array10

array([[0.48036191, 0.17284341, 0.64064328],
       [0.80692038, 0.02836683, 0.503257  ],
       [0.00257853, 0.83779346, 0.66533669]])

In [65]:
print(array10.max(axis=0))
print(array10.max(axis=1))
print(array10.min(axis=0))
print(array10.min(axis=1))

[0.80692038 0.83779346 0.66533669]
[0.64064328 0.80692038 0.83779346]
[0.00257853 0.02836683 0.503257  ]
[0.17284341 0.02836683 0.00257853]


In [74]:
# Arithmetic operations on two arrays.

from numpy import random

array11 = random.random([3,3])
array12 = random.random([3,3])

print(array11)
print()
print(array12)

# Addition
print("\nADD")
print(array11 + array12)
print()
print(np.add(array12,array11))

# Subtraction
print("\nSUB")
print(array11 - array12)
print()
print(np.subtract(array11, array12))

# Multiplication
print("\nMUL")
print(array11 * array12)
print()
print(np.multiply(array11, array12))
print()
print(np.dot(array11, array12))
print()
print(array11.dot(array12))

# Division
print('\nDIV')
print(array11 / array12)
print()
print(np.divide(array11, array12))

[[0.35827681 0.71686724 0.30046451]
 [0.0212015  0.83143838 0.78478605]
 [0.65724487 0.98513542 0.48905028]]

[[0.83213059 0.39839129 0.64700085]
 [0.40385057 0.95847887 0.2717144 ]
 [0.85074079 0.67603411 0.45475993]]

ADD
[[1.1904074  1.11525853 0.94746536]
 [0.42505207 1.78991725 1.05650046]
 [1.50798566 1.66116953 0.9438102 ]]

[[1.1904074  1.11525853 0.94746536]
 [0.42505207 1.78991725 1.05650046]
 [1.50798566 1.66116953 0.9438102 ]]

SUB
[[-0.47385378  0.31847595 -0.34653634]
 [-0.38264907 -0.1270405   0.51307165]
 [-0.19349591  0.30910131  0.03429035]]

[[-0.47385378  0.31847595 -0.34653634]
 [-0.38264907 -0.1270405   0.51307165]
 [-0.19349591  0.30910131  0.03429035]]

MUL
[[0.2981331  0.28559366 0.19440079]
 [0.00856224 0.79691612 0.21323767]
 [0.55914502 0.66598515 0.22240047]]

[[0.2981331  0.28559366 0.19440079]
 [0.00856224 0.79691612 0.21323767]
 [0.55914502 0.66598515 0.22240047]]

[[0.84325775 1.03296072 0.56322777]
 [1.02106878 1.33590476 0.59652042]
 [1.36081608 1.536

In [86]:
array13 = random.random(6)
print(array13)

[0.42543957 0.94672414 0.88116207 0.39022197 0.34596072 0.89566033]


In [111]:
print(array13[4:])

[0.34596072 0.89566033]


In [113]:
array14 = random.random([3,3])
print(array14)

[[0.01434894 0.05392328 0.87215668]
 [0.83452469 0.15117045 0.14552562]
 [0.63659627 0.87030225 0.53738147]]


In [123]:
print(array14[:,:])
print()
print(array14[1:,1:])

[[0.01434894 0.05392328 0.87215668]
 [0.83452469 0.15117045 0.14552562]
 [0.63659627 0.87030225 0.53738147]]

[[0.15117045 0.14552562]
 [0.87030225 0.53738147]]


In [148]:
# Array Sorting

array15 = random.random([3,5])
print(array15)


array15.sort(axis=1, kind='quicksort')
print()
print(array15)

[[0.44919941 0.91480543 0.06066865 0.67175133 0.34007327]
 [0.63354329 0.75627066 0.73013284 0.27272706 0.06101374]
 [0.10801698 0.62347632 0.89936347 0.01669807 0.26265809]]

[[0.06066865 0.34007327 0.44919941 0.67175133 0.91480543]
 [0.06101374 0.27272706 0.63354329 0.73013284 0.75627066]
 [0.01669807 0.10801698 0.26265809 0.62347632 0.89936347]]


In [165]:
# Merging of arrays

array16 = np.arange(1,9).reshape(2,4)
array17 = np.arange(8,0,-1).reshape(2,4)

print(array16)
print()
print(array17)

print()
print()

print(np.vstack((array16, array17)))

print()
print()

print(np.hstack((array16, array17)))

# Using concatenate() Function
print()
print()
array18 = np.concatenate((array16, array17), axis=0)
print(array18)
print()
print()
array19 = np.concatenate((array16, array17), axis=1)
print(array19)

[[1 2 3 4]
 [5 6 7 8]]

[[8 7 6 5]
 [4 3 2 1]]


[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]


[[1 2 3 4 8 7 6 5]
 [5 6 7 8 4 3 2 1]]


[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]


[[1 2 3 4 8 7 6 5]
 [5 6 7 8 4 3 2 1]]


In [184]:
# Splitting of arrays


print(np.vsplit(array18,2))
print(np.hsplit(array18,2))

print('\n'*3)
print(np.vsplit(array19,2))
print(np.hsplit(array19,2))

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[8, 7, 6, 5],
       [4, 3, 2, 1]])]
[array([[1, 2],
       [5, 6],
       [8, 7],
       [4, 3]]), array([[3, 4],
       [7, 8],
       [6, 5],
       [2, 1]])]




[array([[1, 2, 3, 4, 8, 7, 6, 5]]), array([[5, 6, 7, 8, 4, 3, 2, 1]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[8, 7, 6, 5],
       [4, 3, 2, 1]])]


In [191]:
# Accessing the elements of a numpy array

# 1-D Array Using Index.

array20 = np.arange(1,51)
print(array20)

print(array20[-1])
print(array20[38])
print(array20.size)







[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
50
39
50


In [206]:
# 2-D Array Using Slicing.
array21 = np.arange(1,100,5).reshape(5,4)
print(array21)

print(array21[1][2]) # We Can Basically Access the elements using the index also.

print(array21[1:2,2:3]) # This is using slicing method, which basically returns the array.
print(array21[1,2]) # This is basically the same as the indexing but with few updates.

print(array21[:1,:])

[[ 1  6 11 16]
 [21 26 31 36]
 [41 46 51 56]
 [61 66 71 76]
 [81 86 91 96]]
31
[[31]]
31
[[ 1  6 11 16]]


In [213]:
array22 = random.random(7)
print(array22)
print(array22[array22 > 0.345])
print(array22[array22 > 0.3345].size)




[0.91164034 0.84726297 0.83935468 0.75875408 0.38516145 0.0570581
 0.32881806]
[0.91164034 0.84726297 0.83935468 0.75875408 0.38516145]
5


In [215]:
array23 = np.arange(1,400)

print(array23[array23 % 5 == 0])
print(array23[array23 % 5 == 0].size)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265 270
 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355 360
 365 370 375 380 385 390 395]
79
