In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
file1 = pd.read_csv('https://raw.githubusercontent.com/AshishJangra27/Machine-Learning-with-Python-GFG/main/Insurance/insurance.csv')

In [3]:
file1.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
file1['male'] = pd.get_dummies(file1['sex'], drop_first=True).astype('int')

In [5]:
file1

age     sex     bmi  children smoker     region      charges  male
0      19  female  27.900         0    yes  southwest  16884.92400     0
1      18    male  33.770         1     no  southeast   1725.55230     1
2      28    male  33.000         3     no  southeast   4449.46200     1
3      33    male  22.705         0     no  northwest  21984.47061     1
4      32    male  28.880         0     no  northwest   3866.85520     1
...   ...     ...     ...       ...    ...        ...          ...   ...
1333   50    male  30.970         3     no  northwest  10600.54830     1
1334   18  female  31.920         0     no  northeast   2205.98080     0
1335   18  female  36.850         0     no  southeast   1629.83350     0
1336   21  female  25.800         0     no  southwest   2007.94500     0
1337   61  female  29.070         0    yes  northwest  29141.36030     0

[1338 rows x 8 columns]

In [6]:
file1['smoker'] = pd.get_dummies(file1['smoker'], drop_first = True).astype('int')

In [7]:
file1

age     sex     bmi  children  smoker     region      charges  male
0      19  female  27.900         0       1  southwest  16884.92400     0
1      18    male  33.770         1       0  southeast   1725.55230     1
2      28    male  33.000         3       0  southeast   4449.46200     1
3      33    male  22.705         0       0  northwest  21984.47061     1
4      32    male  28.880         0       0  northwest   3866.85520     1
...   ...     ...     ...       ...     ...        ...          ...   ...
1333   50    male  30.970         3       0  northwest  10600.54830     1
1334   18  female  31.920         0       0  northeast   2205.98080     0
1335   18  female  36.850         0       0  southeast   1629.83350     0
1336   21  female  25.800         0       0  southwest   2007.94500     0
1337   61  female  29.070         0       1  northwest  29141.36030     0

[1338 rows x 8 columns]

In [8]:
Region = pd.get_dummies(file1['region']).astype('int')

In [9]:
Region

northeast  northwest  southeast  southwest
0             0          0          0          1
1             0          0          1          0
2             0          0          1          0
3             0          1          0          0
4             0          1          0          0
...         ...        ...        ...        ...
1333          0          1          0          0
1334          1          0          0          0
1335          0          0          1          0
1336          0          0          0          1
1337          0          1          0          0

[1338 rows x 4 columns]

In [10]:
file1 = pd.concat([file1, Region], axis = 1)

In [11]:
file1

age     sex     bmi  children  smoker     region      charges  male  \
0      19  female  27.900         0       1  southwest  16884.92400     0   
1      18    male  33.770         1       0  southeast   1725.55230     1   
2      28    male  33.000         3       0  southeast   4449.46200     1   
3      33    male  22.705         0       0  northwest  21984.47061     1   
4      32    male  28.880         0       0  northwest   3866.85520     1   
...   ...     ...     ...       ...     ...        ...          ...   ...   
1333   50    male  30.970         3       0  northwest  10600.54830     1   
1334   18  female  31.920         0       0  northeast   2205.98080     0   
1335   18  female  36.850         0       0  southeast   1629.83350     0   
1336   21  female  25.800         0       0  southwest   2007.94500     0   
1337   61  female  29.070         0       1  northwest  29141.36030     0   

      northeast  northwest  southeast  southwest  
0             0          0          0          1  
1             0          0          1          0  
2             0          0          1          0  
3             0          1          0          0  
4             0          1          0          0  
...         ...        ...        ...        ...  
1333          0          1          0          0  
1334          1          0          0          0  
1335          0          0          1          0  
1336          0          0          0          1  
1337          0          1          0          0  

[1338 rows x 12 columns]

In [12]:
import statsmodels.api as sm

In [13]:
X = file1.drop(['sex', 'region', 'charges', 'northeast', 'northwest', 'southeast', 'southwest'], axis = 1)

In [14]:
X

age     bmi  children  smoker  male
0      19  27.900         0       1     0
1      18  33.770         1       0     1
2      28  33.000         3       0     1
3      33  22.705         0       0     1
4      32  28.880         0       0     1
...   ...     ...       ...     ...   ...
1333   50  30.970         3       0     1
1334   18  31.920         0       0     0
1335   18  36.850         0       0     0
1336   21  25.800         0       0     0
1337   61  29.070         0       1     0

[1338 rows x 5 columns]

In [15]:
y = file1['charges']

In [16]:
X_constant = sm.add_constant(X)

In [17]:
model = sm.OLS(y, X_constant)

In [18]:
result = model.fit()

In [19]:
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                charges   R-squared:                       0.750
Model:                            OLS   Adj. R-squared:                  0.749
Method:                 Least Squares   F-statistic:                     798.0
Date:                Fri, 19 Apr 2024   Prob (F-statistic):               0.00
Time:                        09:25:24   Log-Likelihood:                -13551.
No. Observations:                1338   AIC:                         2.711e+04
Df Residuals:                    1332   BIC:                         2.715e+04
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.205e+04    951.260    -12.670      0.0

In [20]:
X.drop('male', inplace = True, axis = 1)

In [21]:
X

age     bmi  children  smoker
0      19  27.900         0       1
1      18  33.770         1       0
2      28  33.000         3       0
3      33  22.705         0       0
4      32  28.880         0       0
...   ...     ...       ...     ...
1333   50  30.970         3       0
1334   18  31.920         0       0
1335   18  36.850         0       0
1336   21  25.800         0       0
1337   61  29.070         0       1

[1338 rows x 4 columns]

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
scaler = StandardScaler()

In [24]:
X['age'] = scaler.fit_transform(X['age'].values.reshape(-1, 1))
X['bmi'] = scaler.fit_transform(X['bmi'].values.reshape(-1, 1))

In [25]:
X

age       bmi  children  smoker
0    -1.438764 -0.453320         0       1
1    -1.509965  0.509621         1       0
2    -0.797954  0.383307         3       0
3    -0.441948 -1.305531         0       0
4    -0.513149 -0.292556         0       0
...        ...       ...       ...     ...
1333  0.768473  0.050297         3       0
1334 -1.509965  0.206139         0       0
1335 -1.509965  1.014878         0       0
1336 -1.296362 -0.797813         0       0
1337  1.551686 -0.261388         0       1

[1338 rows x 4 columns]

In [26]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [27]:
from sklearn.svm import SVR


regressor = SVR(kernel = 'rbf', C = 10000, gamma = 0.1)

In [28]:
y_train

25      14001.13380
336     12142.57860
47       3556.92230
106      2331.51900
1269     8615.30000
           ...     
1095     4561.18850
1130     8582.30230
1294    11931.12525
860     46113.51100
1126    10214.63600
Name: charges, Length: 802, dtype: float64

In [29]:
regressor.fit(X_train, y_train)

SVR(C=10000, gamma=0.1)

In [30]:
predict = regressor.predict(X_test)

In [31]:
predict

array([ 8528.58896924,  4912.66803752, 29743.35919625,  9437.50222273,
       28028.48599303,  4800.73056392,  1706.55372399, 14273.63189643,
        3343.64315788, 10494.81067703, 19291.08036489,  7341.2969223 ,
        3952.06724091, 41304.61357421, 43206.58608491, 46257.42781814,
        9883.03336258, 45060.07039682,  8245.02010215, 25938.59411446,
        6012.00087415,  7946.56189771,  1864.27841848,  2316.9661239 ,
       10832.99555812, 10411.8440029 , 12744.12766927,  4713.89056181,
        9158.68073244,  1736.33908805,  8254.00381717, 11551.09614486,
        2179.97526069,  5578.33979593,  3407.3067836 ,  7356.27103195,
        2530.43003092,  7325.9387451 , 24829.2987368 , 40847.51686881,
        4966.68369216,  2786.79345459, 11987.63369216, 12311.64533122,
        5386.27521399, 13030.98711602,  3467.40856964,  4358.56592529,
       38682.01457001,  4998.56393345, 13921.71507936,  2199.75036283,
        6334.16231141,  1631.53515563, 11180.52637831, 10296.73128374,
      

In [32]:
y = y_test.iloc[:].values

In [33]:
y

array([ 9095.06825 ,  5272.1758  , 29330.98315 ,  9301.89355 ,
       33750.2918  ,  4536.259   ,  2117.33885 , 14210.53595 ,
        3732.6251  , 10264.4421  , 18259.216   ,  7256.7231  ,
        3947.4131  , 46151.1245  , 48673.5588  , 44202.6536  ,
        9800.8882  , 42969.8527  ,  8233.0975  , 21774.32215 ,
        5080.096   ,  7441.501   ,  1256.299   ,  2755.02095 ,
       11085.5868  , 10923.9332  , 12644.589   , 18804.7524  ,
        9715.841   ,  1131.5066  , 15828.82173 , 11842.62375 ,
        2020.5523  ,  5693.4305  ,  2904.088   ,  7448.40395 ,
        2597.779   ,  7337.748   , 23887.6627  , 38709.176   ,
        4687.797   ,  2643.2685  , 11674.13    , 12124.9924  ,
        4889.9995  , 12333.828   ,  3579.8287  ,  4391.652   ,
       42124.5153  ,  4463.2051  , 13887.204   ,  1719.4363  ,
       28476.73499 ,  1708.92575 , 10594.2257  , 25333.33284 ,
        3645.0894  , 38746.3551  , 11848.141   , 10564.8845  ,
       13880.949   ,  4753.6368  , 27941.28758 ,  8017.

In [34]:
for i in range(len(predict)):
    print(f" {y[i]} :  {predict[i]}")

 9095.06825 :  8528.588969240729
 5272.1758 :  4912.668037520023
 29330.98315 :  29743.359196251768
 9301.89355 :  9437.502222728606
 33750.2918 :  28028.485993032355
 4536.259 :  4800.730563923664
 2117.33885 :  1706.5537239944551
 14210.53595 :  14273.631896428644
 3732.6251 :  3343.6431578793363
 10264.4421 :  10494.810677028801
 18259.216 :  19291.08036488926
 7256.7231 :  7341.296922301639
 3947.4131 :  3952.0672409143026
 46151.1245 :  41304.61357421289
 48673.5588 :  43206.58608490904
 44202.6536 :  46257.42781814272
 9800.8882 :  9883.033362580023
 42969.8527 :  45060.07039682064
 8233.0975 :  8245.020102154289
 21774.32215 :  25938.594114463885
 5080.096 :  6012.0008741463025
 7441.501 :  7946.561897705575
 1256.299 :  1864.2784184831726
 2755.02095 :  2316.966123903474
 11085.5868 :  10832.99555811597
 10923.9332 :  10411.844002903916
 12644.589 :  12744.127669271991
 18804.7524 :  4713.890561807402
 9715.841 :  9158.680732443232
 1131.5066 :  1736.3390880457264
 15828.82173 

In [35]:
from sklearn.metrics import r2_score

r2_score(y_test, predict)

0.8346048765714105

In [36]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'C': [0.1, 1, 10, 100, 1000, 10000, 100000],
    'gamma': [0.001,0.01, 0.1, 1, 10]
}

# Create SVR model
svr = SVR(kernel='rbf')

# Create GridSearchCV object
grid_search = GridSearchCV(estimator=svr, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)

# Fit the grid search to the data
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Get the best model
best_svr = grid_search.best_estimator_

# Predictions
y_pred_train_best = best_svr.predict(X_train)
y_pred_test_best = best_svr.predict(X_test)

# Evaluating the model
# train_rmse_best = np.sqrt(mean_squared_error(y_train, y_pred_train_best))
# test_rmse_best = np.sqrt(mean_squared_error(y_test, y_pred_test_best))
# print("Train RMSE (Best Model):", train_rmse_best)
# print("Test RMSE (Best Model):", test_rmse_best)


Best Hyperparameters: {'C': 100000, 'gamma': 0.1}


In [37]:
y_pred_test_best

array([ 8554.99805984,  4877.20999461, 31538.82045697,  9356.53636341,
       28363.96846372,  4941.7870046 ,  1760.9270708 , 14319.93857318,
        3378.56956606, 10359.93442739, 18613.53347824,  7336.75870231,
        3929.92845806, 46457.96702254, 49171.31453414, 47556.08990112,
        9517.18016658, 44964.79721825,  8242.34353415, 23979.84982132,
        5307.77426462,  7915.20308094,  1751.77183447,  2170.75114858,
       10701.94161552, 10410.40353878, 12737.55679368,  4856.09383907,
        9151.9897855 ,  1620.80093952,  8139.68817284, 11549.71385353,
        2020.33730187,  5520.79179768,  3358.26896263,  7340.11919442,
        2446.64822435,  7344.28144023, 23557.97594084, 39190.51184289,
        4654.14081894,  2697.2370225 , 11702.61604727, 12335.08894284,
        5360.55331713, 12958.35277729,  3412.34214154,  4497.38137411,
       42545.78039453,  4892.33153657, 13939.32920142,  2064.56778537,
        6426.63298637,  1614.56977452, 11170.92084884, 10202.7716408 ,
      