# Installing Numpy.

In [2]:
import numpy as np
# !pip install numpy ## Command to install the numpy module if not present. 

# Creating A Numpy Array.

In [15]:
lst = [1,2,3,4,5]
print(lst)
print()
array = np.array(lst)
print(array)
print()
print()
print(type(lst))
print()
print(type(array))

[1, 2, 3, 4, 5]

[1 2 3 4 5]


<class 'list'>

<class 'numpy.ndarray'>


# 'arange' function() in NumPy

In [16]:
# arange behaves like a normal range() function in python, but here it creates a numpy array instead of a list.


array2 = np.arange(1,101,2)
print(array2)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


# Multi-Dimensional Arrays in NumPy

In [30]:
array3 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(array3)
print(array3.ndim) # This gives the dimension of the array.

# ------------------------------------------------------------------
# Functions to find the size of the array along with the no of rows and columns.

print(array3.size) # Gives the no of elements in an array.
print(np.size(array3, 0)) # Gives the no of rows.
print(np.size(array3, 1)) # Gives the no of columns.

# -------------------------------------------------------------------
print(array3.dtype) # Gives the data type of the array elements.

array4 = np.array([
    [1.,2.,3.],
    [4.,5.,6.],
    [7.,8.,9.]
])

print(array4.dtype) # Uses the float data type.


# array5 = np.array(['Vikram', 'Kaki'])
# print(array5.dtype)

# --------------------------------------------------------------------
print(array3.shape) # Gives the shape of the array.

# We can also create an n-dimensional array using the ndarray() function, which will create the array with random values.
# array3 = np.ndarray([5,2])
# print(array3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
12
3
4
int32
float64
<U6
(3, 4)


# Functions to create the arrays with same values such as 0's and 1's.

In [37]:
# zeros() function
print()
array5 = np.zeros([3,4], dtype=float) # Creates an array of given size with zeros.
print(array5)
print(f"Array5 D-Type : {array5.dtype}")
print()
# ones() function

print()
array6 = np.ones([3,4], dtype='int64') # Creates an array of given size with ones.
print(array6)
print(f"Array6 D-Type : {array6.dtype}")
print()


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array5 D-Type : float64


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Array6 D-Type : int64


# Eye Function

In [53]:
array7 = np.eye(3,3) # This creates an array of given size with 1's on diagonal elements and 0's on other elements.
print(array7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Empty Function

In [66]:
array8 = np.empty((6,6)) # Gives an uninitialized array
print(array8)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Random Functions.

In [179]:
# np.random.rand() Function.
array9 = np.random.rand(3,3) # Returns an array of give size with random values.
print(array9,end='\n\n\n')



# -------------------------------------------------------------

# np.random.randint() Function.
num1 = np.random.randint(9,100,size=[4,4]) # Returns a random number array between given numbers. If only one number is given, then the first number will be automatically taken as 0.
print(num1, end='\n\n\n')



# ---------------------------------------------------------------

# np.random.randn() Function
array10 = np.random.randn(3,3) # Return an array with random values that follow normal distribution of given size.
print(array10)

[[0.53100088 0.43410163 0.623096  ]
 [0.53490497 0.50649901 0.16781129]
 [0.2632676  0.0100306  0.16038096]]


[[71 89 89 48]
 [20 87 49 68]
 [85 66 83 26]
 [33 45 21 52]]


[[-1.2485604  -0.96143358 -0.55258817]
 [-0.54193818  0.83121045  1.55297545]
 [ 1.54544575  0.95664922 -0.7963433 ]]


# Reshape Function

In [185]:
array11 = np.random.randint(low=1, high=50, size=[4,4])
print("Array Before reshaping.")
print(array11)

print()
print("Array After Reshaping.")
array12 = array11.reshape(2,8)
print(array12)
array13 = array11.reshape([8,2])
print(array13)

Array Before reshaping.
[[ 1  6 24 27]
 [19 17 14 44]
 [36 20  2  8]
 [46 30 10 21]]

Array After Reshaping.
[[ 1  6 24 27 19 17 14 44]
 [36 20  2  8 46 30 10 21]]
[[ 1  6]
 [24 27]
 [19 17]
 [14 44]
 [36 20]
 [ 2  8]
 [46 30]
 [10 21]]


# Linspace Function

In [196]:
array14 = np.linspace(1,100,14) # Returns an array of given size between the given numbers only 1-d array.
print(array14)

[  1.           8.61538462  16.23076923  23.84615385  31.46153846
  39.07692308  46.69230769  54.30769231  61.92307692  69.53846154
  77.15384615  84.76923077  92.38461538 100.        ]


# Flatten Function.

In [213]:
array15 = np.eye(4,4)  # Returns the flatten array .i.e., 1-d array copy of the given array.
print(array15)
print(array15.flatten("K"))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


# LogSpace Function

In [240]:
array16 = np.logspace(1,5,5,base=2)
print(array16)

[ 2.  4.  8. 16. 32.]


# Copy Function

In [242]:
array17 = np.copy(array16)
print(array17, id(array17))
print(array16, id(array16))

[ 2.  4.  8. 16. 32.] 2329219633808
[ 2.  4.  8. 16. 32.] 2329215662288


# Mathematical Functions.

In [256]:
# Max, Min and Sum functions for arrays.


array18 = np.random.randint(1,100,[3,3])
print(f"Array18        : \n{array18}")
print('*'*30)
print(f"Max of array18 : {array18.max()}")
print(f"Min of array18 : {array18.min()}")
print(f"Sum of array18 : {array18.sum()}")
print('*'*30)
print('*'*30)
print("Along the rows and columns.")
print(f"Max element in every column of array18 : {array18.max(axis=0)}")
print(f"Max element in every row of array18 : {array18.max(axis = 1)}")
print(f"Min element in every column of array18 : {array18.min(axis=0)}")
print(f"Min element in every row of array18 : {array18.min(axis = 1)}")
print(f"Sum of elements in every column of array18 : {array18.sum(axis=0)}")
print(f"Sum of elements in every row of array18 : {array18.sum(axis = 1)}")

Array18        : 
[[29  4 82]
 [96 13 47]
 [44 52 17]]
******************************
Max of array18 : 96
Min of array18 : 4
Sum of array18 : 384
******************************
******************************
Along the rows and columns.
Max element in every column of array18 : [96 52 82]
Max element in every row of array18 : [82 96 52]
Min element in every column of array18 : [29  4 17]
Min element in every row of array18 : [ 4 13 17]
Sum of elements in every column of array18 : [169  69 146]
Sum of elements in every row of array18 : [115 156 113]


# Seed Function


#### Gives a pseudo random numbers.
#### Based on the seed's value the random values will be determined. If a same seed value is used we will get the same random numbers.

In [3]:
np.random.seed(seed=5)

array19 = np.random.randint(1,100,[3,3])
print(array19)

array20 = np.random.randint(1,100,[2,2])
print(array20)

array21 = np.random.randn(3,3)
print(array21)

[[79 62 17]
 [74  9 63]
 [28 31 81]]
[[ 8 77]
 [16 54]]
[[ 1.07016333  0.50065426  0.78967626]
 [-0.76902721 -0.18222224 -0.23966088]
 [-1.0915832   3.28631026  0.07453116]]


# Sorting Function

In [289]:
array22 = np.random.randint(1,100,[3,3])
print("Array Before Sorting.")
print(array22)
print("-"*30)
print("Array After Sorting.")
# array22.sort() # Axis is default value is set to -1. Which basically performs the same as the axis = 1
print(np.sort(array22, axis = 1))
print("-"*30)
print("Array after sorting along the columns.")
# array22.sort(axis=0)
print(np.sort(array22, axis = 0))


print("-"*30)
print("-"*30)
# To make the whole array sorted, we can use flatten() function, sort and reshape.
dims = array22.shape # Storing the dimension's values.
# array22 = array22.flatten()
# array22.sort(kind='mergesort')
# array22 = array22.reshape(dims)

array22 = np.reshape(np.sort(array22.flatten()),dims)
print(array22)

Array Before Sorting.
[[35 31 78]
 [98 36 30]
 [ 2 83 21]]
------------------------------
Array After Sorting.
[[31 35 78]
 [30 36 98]
 [ 2 21 83]]
------------------------------
Array after sorting along the columns.
[[ 2 31 21]
 [35 36 30]
 [98 83 78]]
------------------------------
------------------------------
[[ 2 21 30]
 [31 35 36]
 [78 83 98]]


# Mathematical Operations.

In [302]:
array23 = np.random.randint(1,100,[3,3])
print(array23)

[[31 94 79]
 [15 99  9]
 [58 82 41]]


### Addition

In [304]:
print(array23)
print("-"*30)
print(array23+1)
print("-"*30)
print("-"*30)
print(np.add(array23,1))

[[31 94 79]
 [15 99  9]
 [58 82 41]]
------------------------------
[[ 32  95  80]
 [ 16 100  10]
 [ 59  83  42]]
------------------------------
------------------------------
[[ 32  95  80]
 [ 16 100  10]
 [ 59  83  42]]


### Subtraction

In [305]:
print(array23)
print("-"*30)
print(array23 - 1)
print("-"*30)
print("-"*30)
print(np.subtract(array23,1))

[[31 94 79]
 [15 99  9]
 [58 82 41]]
------------------------------
[[30 93 78]
 [14 98  8]
 [57 81 40]]
------------------------------
------------------------------
[[30 93 78]
 [14 98  8]
 [57 81 40]]


### Multiplication

In [306]:
print(array23)
print("-"*30)
print(array23 * 2)
print("-"*30)
print("-"*30)
print(np.multiply(array23,2))

[[31 94 79]
 [15 99  9]
 [58 82 41]]
------------------------------
[[ 62 188 158]
 [ 30 198  18]
 [116 164  82]]
------------------------------
------------------------------
[[ 62 188 158]
 [ 30 198  18]
 [116 164  82]]


### Division

In [308]:
print(array23)
print("-"*30)
print(array23 / 2)
print("-"*30)
print("-"*30)
print(np.divide(array23,2))

[[31 94 79]
 [15 99  9]
 [58 82 41]]
------------------------------
[[15.5 47.  39.5]
 [ 7.5 49.5  4.5]
 [29.  41.  20.5]]
------------------------------
------------------------------
[[15.5 47.  39.5]
 [ 7.5 49.5  4.5]
 [29.  41.  20.5]]


### Matrix Multiplication

In [331]:
# Creating two arrays.
array24 = np.random.randint(1,100,[3,3])
array25 = np.random.randint(1,100,[3,4])
print(array23)
print("-"*30)
print(array24)
print("-"*30)
print(array25)

[[31 94 79]
 [15 99  9]
 [58 82 41]]
------------------------------
[[ 1  7 27]
 [ 5 82 13]
 [96 64 99]]
------------------------------
[[62 95 92 76]
 [63 52  3 97]
 [20  8 77 67]]


##### Normal Matrix Multiplication

In [332]:
print(array23 * array24) # Multiplies the corresponding elements.

[[  31  658 2133]
 [  75 8118  117]
 [5568 5248 4059]]


##### Dot Matrix Multiplication

In [333]:
print(array23.dot(array24))
print(array23 @ array24)
print("-"*30)
print("-"*30)
print(array24.dot(array25))
print(array24 @ array25)

[[ 8085 12981  9880]
 [ 1374  8799  2583]
 [ 4404  9754  6691]]
[[ 8085 12981  9880]
 [ 1374  8799  2583]
 [ 4404  9754  6691]]
------------------------------
------------------------------
[[ 1043   675  2192  2564]
 [ 5736  4843  1707  9205]
 [11964 13240 16647 20137]]
[[ 1043   675  2192  2564]
 [ 5736  4843  1707  9205]
 [11964 13240 16647 20137]]


### Power Function


In [337]:
print(array24 ** 2)

[[   1   49  729]
 [  25 6724  169]
 [9216 4096 9801]]


# Percentile Function

In [345]:
print(np.percentile(array24, 100, axis=1))
print(np.percentile(array24, 100, axis=0))

[27. 82. 99.]
[96. 82. 99.]


# Mean, Std and Variance.

In [349]:
array26 = np.random.randint(1,100,[2,4])
print(array26)

[[75 71 49 56]
 [52 98 40  1]]


### Mean

In [352]:
print(array26)
print(f"Mean of the array26 : {array26.mean()}")
print(f"Mean among the rows : {array26.mean(axis=1)}")
print(f"Mean among the columns : {array26.mean(axis=0)}")

[[75 71 49 56]
 [52 98 40  1]]
Mean of the array26 : 55.25
Mean among the rows : [62.75 47.75]
Mean among the columns : [63.5 84.5 44.5 28.5]


# Std

In [353]:
print(array26)
print(f"Std of the array26 : {array26.std()}")
print(f"Std among the rows : {array26.std(axis=1)}")
print(f"Std among the columns : {array26.std(axis=0)}")

[[75 71 49 56]
 [52 98 40  1]]
Std of the array26 : 26.672785756272255
Std among the rows : [10.63896142 34.6003974 ]
Std among the columns : [11.5 13.5  4.5 27.5]


# Variance

In [354]:
print(array26)
print(f"Variance of the array26 : {array26.var()}")
print(f"Variance among the rows : {array26.var(axis=1)}")
print(f"Variance among the columns : {array26.var(axis=0)}")

[[75 71 49 56]
 [52 98 40  1]]
Variance of the array26 : 711.4375
Variance among the rows : [ 113.1875 1197.1875]
Variance among the columns : [132.25 182.25  20.25 756.25]


# Filtering in arrays.

In [366]:
array27 = np.linspace(1,100,10)
print(array27)
print(array27 > 45)
print(array27[array27 > 45])


# We can even replace the values.
array27[array27 < 45] = 45
print(array27)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[False False False False False  True  True  True  True  True]
[ 56.  67.  78.  89. 100.]
[ 45.  45.  45.  45.  45.  56.  67.  78.  89. 100.]


# Transpose of Arrays [ 2-d are greater dimension arrays only]

In [389]:
array28 = np.logspace(3,8,10,base=2).reshape([2,5])
print(array28)

print("*"*30)
print("Transpose of array28")
print(array28.T)
# print(array28.transpose()) Same as the above but as a function not as member

[[  8.          11.75787594  17.28095582  25.39841683  37.32892927]
 [ 54.8636149   80.63494719 118.51196317 174.18112002 256.        ]]
******************************
Transpose of array28
[[  8.          54.8636149 ]
 [ 11.75787594  80.63494719]
 [ 17.28095582 118.51196317]
 [ 25.39841683 174.18112002]
 [ 37.32892927 256.        ]]
[[  8.          54.8636149 ]
 [ 11.75787594  80.63494719]
 [ 17.28095582 118.51196317]
 [ 25.39841683 174.18112002]
 [ 37.32892927 256.        ]]


# Inverse

In [385]:
# Inverse of the matrix
array29 = np.linspace(1,10,4).reshape([2,2])
print(array29)
print("Inverse.")
print(np.linalg.inv(array29))

print(array29 @ np.linalg.inv(array29))

[[ 1.  4.]
 [ 7. 10.]]
Inverse.
[[-0.55555556  0.22222222]
 [ 0.38888889 -0.05555556]]
[[1. 0.]
 [0. 1.]]


# Where Function

In [399]:
array30 = np.random.randint(1,100,13)
print(array30)
print(np.where(array30 % 2 == 0, 'Even',array30))

[35 48 59  2 19 54  2 86 62 81 18 54 74]
['35' 'Even' '59' 'Even' '19' 'Even' 'Even' 'Even' 'Even' '81' 'Even'
 'Even' 'Even']


# Merging Arrays.

In [403]:
array31 = np.random.randint(1,100,[2,4])
array32 = np.random.randint(1,100,[2,4])
print(array31)
print(array32)

[[82 56  4 30]
 [21 43 10 65]]
[[73  2 86 91]
 [83 65 62 65]]


### Using concatenate() Function

In [404]:
print(np.concatenate([array31, array32],axis=1)) # Concatenates the array's row wise.
print(np.concatenate([array31, array32],axis=0)) # Concatenates the array's column wise

[[82 56  4 30 73  2 86 91]
 [21 43 10 65 83 65 62 65]]
[[82 56  4 30]
 [21 43 10 65]
 [73  2 86 91]
 [83 65 62 65]]


### Using vstack() Function.

In [408]:
print(np.vstack([array31,array32])) # Adds the array's column wise.

[[82 56  4 30]
 [21 43 10 65]
 [73  2 86 91]
 [83 65 62 65]]


### Using hstack() Function.

In [407]:
print(np.hstack((array31, array32))) # Adds the array's rows wise

[[82 56  4 30 73  2 86 91]
 [21 43 10 65 83 65 62 65]]


# Splitting The Arrays.

In [426]:
array33 = np.arange(1,17).reshape(4,4)
print(array33)
print()
print(np.split(array33,2, axis=0))
print(np.split(array33,2, axis=1))



print(np.vsplit(array33,2))
print(np.hsplit(array33,2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


# Turning pics into numpy arrays.

In [427]:
from matplotlib.image import imread

In [3]:
import os

In [429]:
os.getcwd()

'C:\\Users\\Asus\\Desktop\\DataScieneLearning\\Libraries\\NoteBooks'

In [430]:
os.chdir('../')

In [431]:
os.getcwd()

'C:\\Users\\Asus\\Desktop\\DataScieneLearning\\Libraries'

In [5]:
os.chdir('C:\\Users\\Asus\\OneDrive\\Pictures')

In [4]:
os.getcwd()

'C:\\Users\\Asus\\Desktop\\DataScieneLearning\\Libraries\\NoteBooks'

In [8]:
from matplotlib.image import imread as ir
# ! P1.PNG
image1 = ir('P1.PNG')
print(image1.shape)
print(image1.max())
print(image1.min())
print(image1.var())

(885, 741, 4)
1.0
0.0
0.013405425
